# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lasso_grid_sparse <- function(beta_grid, A_add, A_add_size, var_order, grid_seq, A, A_size, S, S_size, R, R_size, Xty, XtX, lambda, thresh, maxit, null_dev, lambda_0, early_stopping) {
    .Call(`_SubsetGridRegression_lasso_grid_sparse`, beta_grid, A_add, A_add_size, var_order, grid_seq, A, A_size, S, S_size, R, R_size, Xty, XtX, lambda, thresh, maxit, null_dev, lambda_0, early_stopping)
}

lasso_grid <- function(beta_grid, A_add, A_add_size, var_order, grid_seq, A, A_size, S, S_size, R, R_size, Xty, XtX, lambda, thresh, maxit) {
    .Call(`_SubsetGridRegression_lasso_grid`, beta_grid, A_add, A_add_size, var_order, grid_seq, A, A_size, S, S_size, R, R_size, Xty, XtX, lambda, thresh, maxit)
}

